# Generated by Django 4.2.3 on 2023-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
