# Generated by Django 4.2.3 on 2023-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_usuario_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
