# Generated by Django 4.2.3 on 2023-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
