# Generated by Django 4.2.3 on 2023-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_usuario_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
