# Generated by Django 4.2.3 on 2023-08-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_medico_especialidad_alter_review_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='rating',
        ),
    ]
