# Generated by Django 4.2.3 on 2023-09-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_alter_medico_especialidad_alter_review_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
