# Generated by Django 4.2.3 on 2023-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0007_medico_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
