# Generated by Django 4.2.3 on 2023-09-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_alter_medico_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelMedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='medico.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='medico.medico')),
            ],
            options={
                'ordering': ['especialidad', 'medico'],
            },
        ),
    ]
