# Generated by Django 4.2.3 on 2023-09-20 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0009_relmedicoespecialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['obra_social'],
            },
        ),
        migrations.AlterModelOptions(
            name='relmedicoespecialidad',
            options={'ordering': ['especialidad', 'medico'], 'verbose_name_plural': 'Relaciones Medico-Especialidad'},
        ),
        migrations.AddField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relmedicoespecialidad',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_especialidad', to='medico.medico'),
        ),
        migrations.CreateModel(
            name='RelMedicoObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_obra', to='medico.medico')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_sociales', to='medico.obrasocial')),
            ],
            options={
                'verbose_name_plural': 'Relaciones Medico-Obra Social',
                'ordering': ['obra_social', 'medico'],
            },
        ),
    ]
