# Generated by Django 4.2.3 on 2023-09-10 23:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

#    dependencies = [
#        ('medico', '0009_relmedicoespecialidad'),
#   ]

    operations = [
        migrations.AlterModelOptions(
            name='relmedicoespecialidad',
            options={'ordering': ['especialidad', 'medico'], 'verbose_name_plural': 'Relaciones Medico-Especialidad'},
        ),
        migrations.AddField(
            model_name='relmedicoespecialidad',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-22 14:08:44.031184'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='especialidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad_Review', to='medico.especialidad'),
            preserve_default=False,
        ),
    ]
