# Generated by Django 4.2.3 on 2023-09-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0011_remove_medico_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
